const { sendToImgbb } = require('./imgbb');
const { sendToGooey } = require('./gooey');
const { makeStory } = require('./cohere');

console.log("Hello World!");

let ibb_url = 'a';

document.getElementById('photo').addEventListener('change', async function(event) {
    ibb_url = await sendToImgbb(event);
    console.log(ibb_url);
});

document.getElementById('img-form').addEventListener('submit', async function(event) {
    const location = document.getElementById('location').value;
    const time = document.getElementById('time').value;
    const storyblock = document.getElementById('story');

    const h2 = document.createElement('h2');
    h2.textContent = `${location} during the ${time}`;
    storyblock.appendChild(h2);

    const h6 = document.createElement('h6');
    h6.textContent = "content generated by cohere.com";
    storyblock.appendChild(h6);
    
    await sendToGooey(event, ibb_url, location, time);
    await makeStory(location, time);
});